### ISSUE TITLE
update to EKS 1.23

### ISSUE THREAD

**Issue by satya-dillikar** [aws-quickstart/quickstart-vmware-tanzu-application-platform#107]
Please refer to 
https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23
https://github.com/pivotal/docs-tap/pull/1478

Looks like "EBS CSI Driver installed" is required on cluster.

**Comment by leclaist** [comment]
@tlindsay42 do we have support in the nested stack for k8s version 1.23 yet? we are wanting to offer 1.23 in our quickstart but if the nested stack does not allow for it, the build will not succeed. cc @satya-dillikar

**Comment by tlindsay42** [comment]
EKS v1.23 support is available now, thanks to VMware's influence per the separate thread. Sending an email with additional details.

**Comment by leclaist** [comment]
> EKS v1.23 support is available now, thanks to VMware's influence per the separate thread. Sending an email with additional details.

Thank you for the quick work on this!

**Comment by tlindsay42** [comment]
Closed incorrectly. Updates were completed for the EKS QS submodule, but not the templates.

**Comment by hoegaarden** [comment]
We are [currently running 1.24](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/2c92d99369a41875d75825236432d0a355b138dc/templates/aws-tap-entrypoint-existing-vpc.template.yaml#L502), so I think we can close that off.
@tlindsay42
