### ISSUE TITLE
Deployment guide feedback

### ISSUE THREAD

**Issue by spagno** [aws-quickstart/quickstart-vmware-tanzu-application-platform#108]
Section heading: [Deployment steps](http://aws-quickstart.github.io/quickstart-vmware-tanzu-application-platform/#_deployment_steps)
Documentation issue description:
The statement of "Deployment takes about 2 hours to complete" feels out of place. Maybe more suited to step 7
Also, as relocate is "no" by default, change the statement to 1 hour (or add a note of 1 hours without relocate and two with)

**Comment by tlindsay42** [comment]
> The statement of "Deployment takes about 2 hours to complete" feels out of place. Maybe more suited to step 7

@spagno, this is part of the boilerplate documentation template used in all Quick Start documentation, so changing this would require changing the documentation for all Quick Starts (once the submodule is bumped in each). If you still want to proceed, submit a PR to update https://github.com/aws-ia/aws-ia-documentation-base-common/blob/main/deployment_steps_cfn.adoc and then tag @DelfinGala in the comments. 

> Also, as relocate is "no" by default, change the statement to 1 hour (or add a note of 1 hours without relocate and two with)

Agreed. @aaronmeza and/or @satya-dillikar: do you approve? 

@spagno: if either approves, this documentation variable is located here: https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/doc-edits/docs/deployment_guide/partner_editable/_settings.adoc#L15. To update it, submit a PR to the `doc-edits` branch. Once either approve, then tag @DelfinGala to deploy. If you run into any issues, tag me. Alternatively, ask Satya for my contact info to reach out directly.

**Comment by satya-dillikar** [comment]
I approve.
