### ISSUE TITLE
CodeBuild and the easy_install requirement for the CloudFormation Helper scripts

### ISSUE THREAD

**Issue by satya-dillikar** [aws-quickstart/quickstart-vmware-tanzu-application-platform#20]
**Summary**:
I2. The TAP installation is around 2hr. How to give user feedback or notification about the completed process (success or failure).
R2. We don’t have a great way to do this right now because of our design decision to implement the installation process in an Ubuntu EC2 instance versus CodeBuild and the easy_install requirement for the CloudFormation Helper scripts. Working on this though. Much larger issue than just this project.

**Suggested Assignee**: AWS
**Priority**: P3

**Comment by hoegaarden** [comment]
We are meanwhile using cfn-signal and some [WaitConditions](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/2c92d99369a41875d75825236432d0a355b138dc/templates/aws-tap-entrypoint-existing-vpc.template.yaml#L2221-L2267) to report back from the install script, so I think we can close this off.
@tlindsay42

**Comment by satya-dillikar** [comment]
Closing this as we have an alternate solution.
