### ISSUE TITLE
switch to using the tanzunet API to download product files

### ISSUE THREAD

**Issue by satya-dillikar** [aws-quickstart/quickstart-vmware-tanzu-application-platform#34]
Currently, we are using pivnet CLI to download product files.
This cli is not officially supported by VMware.

Todo:
1) switch to using the Tanzunet API 
2) add checksum validation for the downloaded file.

Label: Backlog
Assignee: Satya
Priority: P3

**Comment by hoegaarden** [comment]
We decided to switch out the `pivnet` CLI for the `om` CLI, which gives us similar outcomes and is supported/patched/maintained. No need to implement TanzuNet interactions ourselves. This came in recently with #149 and thus this issue can be closed.
@tlindsay42
