### ISSUE TITLE
Deployment guide feedback

### ISSUE THREAD

**Issue by dineshtripathi30** [aws-quickstart/quickstart-vmware-tanzu-application-platform#67]
Section heading: Tanzu Network Username parameter shows as secret ** 
Documentation issue description:
When we enter a Tanzu network username during Cloudformation template deployment, it shows as ***. I am wondering if we can show that as a plain string rather than as secret value.

https://aws-quickstart.github.io/quickstart-vmware-tanzu-application-platform/#_parameter_reference

**Comment by tlindsay42** [comment]
@satya-dillikar ^^

**Comment by satya-dillikar** [comment]
ok, assigned this to me.
cc: @tlindsay42
