### ISSUE TITLE
Provide how to create IAM Roles

### ISSUE THREAD

**Issue by making** [aws-quickstart/quickstart-vmware-tanzu-application-platform#80]
> This EC2 instance should have IAM roles attached to access the EKS cluster & ECR Repos.
https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/main/tap-setup-scripts/TAP-SETUP-README.md#prerequisites

Having IAM Roles is a prerequisite but it would be very helpful if you provide the way to create it especially for those who are not familiar with IAM (like me).
Thanks!

**Comment by tlindsay42** [comment]
Hi @making! 

The necessary [IAM Role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html) is automatically created as part of the deployment ([code reference](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/a883126d20ce292fed85d28a3eeaf4072a6c45b1/templates/aws-tap-entrypoint-existing-vpc.template.yaml#L933-L1055)) and attached to the Linux bastion host EC2 instance via an [Instance Profile](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#ec2-instance-profile) ([code reference](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/blob/a883126d20ce292fed85d28a3eeaf4072a6c45b1/templates/aws-tap-entrypoint-existing-vpc.template.yaml#L1056-L1063)), so all of the necessary permissions are already available.

@satya-dillikar Do you think we need to update the docs here to make this clearer?

**Comment by making** [comment]
OK, the doc may be outdated.
I was able to create the IAM Role by referring the template. Thanks!

**Comment by satya-dillikar** [comment]
Aha, I missed this. 
I think the file [TAP-SETUP-README.md](https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform/tree/main/tap-setup-scripts)/TAP-SETUP-README.md should not be exposed to users as it is only for internal reference.

We can remove this file now.
cc: @tlindsay42
