### ISSUE TITLE
AWSQS::EKS::Cluster	CREATE_FAILED	Internal Failure

### ISSUE THREAD

**Issue by satya-dillikar** [aws-quickstart/quickstart-vmware-tanzu-application-platform#99]
Cluster Control Plan - Internal Failure

Commands: 
git clone https://github.com/aws-quickstart/quickstart-vmware-tanzu-application-platform.git
git submodule update --init --recursive
source ~/virtual-env/venv-py-3.8/bin/activate
update .taskcat_overrides.yml
taskcat upload
taskcat test run --no-delete --keep-failed

See screenshots.

PS: 
I showed this problem to Troy over the zoom meeting.

![eks-control-plane-internal-failure- Screen Shot 2022-08-11 at 1 48 35 PM](https://user-images.githubusercontent.com/37601587/184249218-27893ce5-d59c-448b-ae9a-bd8f94a05b49.png)
![eks-control-plane-internal-failure- Screen Shot 2022-08-11 at 1 48 14 PM](https://user-images.githubusercontent.com/37601587/184249227-ee0dd940-665e-44c7-8332-fcc97b40fc33.png)
![eks-control-plane-internal-failure- Screen Shot 2022-08-11 at 1 48 03 PM](https://user-images.githubusercontent.com/37601587/184249228-e74a4be4-8187-4193-aea5-c57964d45d58.png)

**Comment by tlindsay42** [comment]
Per separate discussion, I wasn't able to reproduce. We'll circle back to this.

**Comment by satya-dillikar** [comment]
Same issue from UI as well.

**Comment by satya-dillikar** [comment]
some related threads in https://github.com/aws-quickstart/quickstart-amazon-eks/issues/208

**Comment by satya-dillikar** [comment]
This issue might be specific to a particular setup because of not cleaning up resources from previous deployments or any stale resources.
 
Workaround:

- Remove all stacks including eks-quickstart-RegionalSharedResources & eks-quickstart-AccountSharedResources 
- Manually cleanup leftover IAM roles with "*qs*" and "*quick*" substrings and/or
- run submodules/quickstart-amazon-eks/build/clean-aws.sh script  from github repo (if available) 


Thanks

**Comment by tlindsay42** [comment]
Per our separate conversation, the `clean-aws.sh` script should remove all of the necessary stacks and resources. ?

**Comment by satya-dillikar** [comment]
yes. lets close this for now.
